plugins {
	id 'net.fabricmc.fabric-loom' version '1.16.0-alpha.13'
	id 'maven-publish'
}

version = project.mod_version + "+mc" + project.minecraft_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()

	maven {
		url = "https://maven.parchmentmc.org"
	}

	maven {
		url = "https://api.modrinth.com/maven"
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"

	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	implementation "maven.modrinth:modmenu:${project.modmenu_version}"
	localRuntime "maven.modrinth:modmenu:${project.modmenu_version}"

	implementation "com.google.code.gson:gson:2.10.1"
	
	compileOnly "io.github.llamalad7:mixinextras-common:0.3.5"
	annotationProcessor "io.github.llamalad7:mixinextras-common:0.3.5"
	implementation "io.github.llamalad7:mixinextras-fabric:0.3.5"
	
	// Brigadier is included in Minecraft, but we need to ensure it's available
	implementation "com.mojang:brigadier:1.0.18"
}

loom {
	mixin {
		defaultRefmapName.set("dimensionviewer.refmap.json")
	}
	runs {
		server {
			runDir "runs/server"
		}
	}
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
	
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
